apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-dns
spec:
  clusterIP: None
        #  externalIPs:
          #  - 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-dns
